/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package didactic.parakeet;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public int sumar() {
        return 2 + 2;
    }
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
